version: '3'
services:
  web:
    image: "appsvcsample/flaskapp"
    # source code for this image repoe come from "Get started with Docker Compose" on docker.com
    ports:
     - "80:80"
  redis:
    image: "redis:alpine"
